services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8042:8042"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
    stdin_open: true
    tty: true
